#!/bin/sh

echo "Initialization sequence activated..."

cd assets/css/scss/_libs/                                    && \
bourbon install                                              && \
neat install                                                 && \
cd ../../../../                                              && \
npm install

echo "Project successfully installed!"

git status
