#!/bin/sh

echo "Initialization sequence activated..."

cd assets/css/scss/_libs/               && \
bourbon install                         && \
neat install                            && \
cd ../../../../                         && \
npm install                             && \
rm $0

echo "Project successfully installed!"
